// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgOUd3j9vYMoHRL7V-2-qiHbqaekBEDPw',
    appId: '1:206416761924:web:8adea860072b0cf4491811',
    messagingSenderId: '206416761924',
    projectId: 'flutter-login-41e1b',
    authDomain: 'flutter-login-41e1b.firebaseapp.com',
    databaseURL: 'https://flutter-login-41e1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-login-41e1b.appspot.com',
    measurementId: 'G-MJ4PSFL6SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpfg4_GmBg_sv7Kh5wWMbzr9AHUhn-Yr8',
    appId: '1:206416761924:android:45ae2951990cb06a491811',
    messagingSenderId: '206416761924',
    projectId: 'flutter-login-41e1b',
    databaseURL: 'https://flutter-login-41e1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-login-41e1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8uu4MRsUZc0bPLl10ToNmaVxGbI0Hxcc',
    appId: '1:206416761924:ios:0c1a5a2a58100df9491811',
    messagingSenderId: '206416761924',
    projectId: 'flutter-login-41e1b',
    databaseURL: 'https://flutter-login-41e1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-login-41e1b.appspot.com',
    iosClientId: '206416761924-m26h04nj1mog4ck6iippurut6uae32f9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8uu4MRsUZc0bPLl10ToNmaVxGbI0Hxcc',
    appId: '1:206416761924:ios:24e32f54bbf00ba2491811',
    messagingSenderId: '206416761924',
    projectId: 'flutter-login-41e1b',
    databaseURL: 'https://flutter-login-41e1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-login-41e1b.appspot.com',
    iosClientId: '206416761924-630bf9dthgstqnhto1q58nq3tfqr2olv.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdsc.RunnerTests',
  );
}
